# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NYURespondents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('myNeighborhood', models.CharField(default='', max_length=255)),
                ('q1', models.CharField(default='', max_length=255)),
                ('q2', models.CharField(default='', max_length=255)),
                ('q3', models.CharField(default='', max_length=255)),
                ('q4', models.CharField(default='', max_length=255)),
                ('q5', models.CharField(default='', max_length=255)),
                ('whereIGo', models.TextField(default='')),
            ],
        ),
    ]
