# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='neighborhoodNYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoroCode', models.IntegerField(default=0)),
                ('BoroName', models.CharField(default='', max_length=255)),
                ('CountyFIPS', models.IntegerField(default=0)),
                ('NTACode', models.CharField(default='', max_length=255)),
                ('NTAName', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nyurespondents',
            name='myNeighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.neighborhoodNYC'),
        ),
    ]
