# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160623_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='whereIGo',
            new_name='knowBestPlaces',
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='howLongLivedNeighborhood',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestNeighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowbestneighborhoods', to='website.neighborhoodNYC'),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='knowBestq9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nyurespondents',
            name='myNeighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myneighborhoods', to='website.neighborhoodNYC'),
        ),
    ]
