# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160624_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq1',
            new_name='circleq1',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq10',
            new_name='circleq10',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq2',
            new_name='circleq11',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq3',
            new_name='circleq12',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq4',
            new_name='circleq13',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq5',
            new_name='circleq14',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq6',
            new_name='circleq15',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq7',
            new_name='circleq16',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq8',
            new_name='circleq17',
        ),
        migrations.RenameField(
            model_name='nyurespondents',
            old_name='knowBestq9',
            new_name='circleq18',
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq19',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq20',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='circleq9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q11',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q12',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q13',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q14',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q15',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q16',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q17',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q18',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q19',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyurespondents',
            name='q20',
            field=models.CharField(default='', max_length=255),
        ),
    ]
