repos= "http://cran.us.r-project.org"
install.packages('rgdal',repos=repos)
install.packages('raster',repos=repos)
install.packages('jsonlite',repos=repos)
#dyn.load('/install.packages/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/server/libjvm.dylib')
install.packages('rJava',repos=repos)
install.packages('foreach',repos=repos)
install.packages('doParallel',repos=repos)
install.packages('rgeos',repos=repos)
install.packages('geojsonio',repos=repos)
install.packages('httr',repos=repos)
install.packages('Hmisc',repos=repos)
install.packages('ggplot2',repos=repos)
install.packages('lubridate',repos=repos)
install.packages('plyr',repos=repos)
install.packages('sp',repos=repos)
